[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.1"
actix-web = { version = "4.10.2", features = ["__compress"] }
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
